#!/bin/bash

# استخراج البيانات
name=$(jq -r '.name' data.json | sed 's/\b\(.\)/\u\1/')
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json | sed 's/\b\(.\)/\u\1/')

# تحويل الوحدات
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height/10}") #from decimeters to meters
formatted_weight=$(awk "BEGIN {printf \"%d\", $weight/10}")   #from hectograms to kilograms

# الطباعة المطلوبة
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
